project_id = "blhztdikukgwuhkhootf"

[functions.signal]
verify_jwt = false

[functions.diagnose]
verify_jwt = false

[functions.evaluate]
verify_jwt = false

[functions.mostar-chat]
verify_jwt = false
