// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

import { env, requireEnv } from '@/lib/envConfig';

const SUPABASE_URL = requireEnv(env.supabaseUrl, 'Supabase URL');
const SUPABASE_PUBLISHABLE_KEY = requireEnv(env.supabaseAnonKey, 'Supabase publishable key');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
